PORT = 'port'
HOST = 'host'
UPLOAD_TIME = 'upload_time'
LAST_TIME = 'last_get'
REQUEST_FILE = "request_file"
REQUEST_UPLOAD = "request_upload"
ERROR_UPLOAD = "can't upload a file"
SEND_FILE = "send_file"
UPLOADED_SUCCESS = "uploaded successfully"
UPLOADED_DENIED = "UPLOAD_DENIED"
UPLOAD_APPROVED = "upload_approved"
UPLOADED_FAILED = "UPLOADED_FAILED"
BUFFER_SIZE = 1024
SUBFILE_SIZE = 1048576
