PORT = 'port'
HOST = 'host'
UPLOAD_TIME = 'upload_time'
LAST_TIME = 'last_get'
REQUEST_FILE = b"request_file"
REQUEST_UPLOAD = b"request_upload"
ERROR_UPLOAD = b"can't upload a file"
SEND_FILE = b"send_file"
UPLOADED_SUCCESS = b"uploaded successfully"
UPLOAD_DENIED = b"UPLOAD_DENIED"
UPLOAD_APPROVED = b"upload_approved"
UPLOADED_FAILED = b"UPLOADED_FAILED"
DHT_SMALL = "cant upload because the DHT is too small for such a file. find friends"
BUFFER_SIZE = 4096
SUBFILE_SIZE = 20
PAILIER_KEY_SIZE = 3072
